Repository RDycore/RDycore, pull requests merged in 2023-12, with the labels that each got.

#113 Corrects the setting of values in a CeedVector
  include/private/rdysweimpl.h
  src/rdydata.c
  src/swe/swe_ceed.c
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
  src/time_series.c
Labels: bug-fix, libceed

#110 Updated input spec with more descriptive regions/boundaries
  docs/user/input.md
  driver/tests/swe_roe/Houston1km.DirichletBC.yaml
  driver/tests/swe_roe/ex2b.yaml
  driver/tests/swe_roe/ex2b_dirichlet_bc.yaml
  driver/tests/swe_roe/ex2b_ic_file.yaml
  driver/tests/swe_roe/four_mounds_60x24.yaml
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  src/CMakeLists.txt
  src/f90-mod/tests/coupling.yaml
  src/print_config.c
  src/rdycore.c
  src/rdysetup.c
  src/tests/CMakeLists.txt
  src/tests/test_yaml_input.c
  src/xdmf_output.c
  src/yaml_input.c
Labels: documentation, enhancement, I/O

#117 Updated Docker scripts to build int32 and int64 PETSc images.
  .github/workflows/auto_test.yml
  CMakeLists.txt
  README.md
  docs/user/input.md
  driver/main.c
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/Houston1km.DirichletBC.yaml
  driver/tests/swe_roe/ex2b_ic_file.yaml
  driver/tests/swe_roe/four_mounds_60x24.yaml
  include/rdycore.h.in
  share/conditions/DamBreak_grid5x10_wetdownstream.ic.int32.bin
  share/conditions/DamBreak_grid5x10_wetdownstream.ic.int64.bin
  share/conditions/Houston1km.bc.int32.bin
  share/conditions/Houston1km.bc.int64.bin
  share/conditions/Houston1km.ic.int32.bin
  share/conditions/Houston1km.ic.int64.bin
  share/conditions/Houston1km.rain.int32.bin
  share/conditions/Houston1km.rain.int64.bin
  share/conditions/four_mounds_60x24.ic.int32.bin
  share/conditions/four_mounds_60x24.ic.int64.bin
  share/materials/manning_four_mound_60x24.int32.bin
  share/materials/manning_four_mound_60x24.int64.bin
  share/materials/manning_grid5x10.int32.bin
  share/materials/manning_grid5x10.int64.bin
  src/rdyadvance.c
  src/rdysetup.c
  src/time_series.c
  src/yaml_input.c
  tools/Dockerfile.petsc
  tools/build-petsc-docker-images.sh
Labels: testing, petsc, libceed

#79 Fixes an issue with preloading, and removes some unnecessary code.
  .github/workflows/auto_test.yml
  README.md
  src/rdyadvance.c
Labels: petsc, bug-fix
