Repository RDycore/RDycore, pull requests merged in 2023-03, with the labels that each got.

#25 Minor fixes for building cmocka on Perlmutter
  external/CMakeLists.txt
  src/rdymesh.c
Labels: build system, testing

#24 Implemented file-based initial conditions (and default boundary edge assignment)
  README.md
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/ex2b_ic_file.yaml
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  share/CMakeLists.txt
  share/initial_conditions/DamBreak_grid5x10_wetdownstream.IC
  share/meshes/DamBreak_grid5x10.exo
  src/physics_swe.c
  src/rdycore.c
  src/rdysetup.c
  src/read_config_file.c
Labels: enhancement, mesh and discretization

#26 Fixes the friction computation
  src/physics_swe.c
Labels: bug-fix
