Repository RDycore/RDycore, pull requests merged in 2023-10, with the labels that each got.

#82 Removes setting the number of quadrature points
  .github/workflows/auto_test.yml
  src/physics_swe.c
  tools/Dockerfile.petsc
Labels: petsc

#84 Allowing the log file to be overridden with a function call
  include/rdycore.h.in
  src/f90-mod/rdycore.F90
  src/rdysetup.c
Labels: enhancement, I/O, E3SM coupling

#87 Adding a self-contained test for coupling with E3SM.
  include/rdycore.h.in
  src/f90-mod/CMakeLists.txt
  src/f90-mod/tests/CMakeLists.txt
  src/f90-mod/tests/coupling.yaml
  src/f90-mod/tests/test_coupling.F90
  src/rdysetup.c
Labels: testing, E3SM coupling

#86 Setting Vec and Mat types appropriately when we use CEED.
  include/private/rdycoreimpl.h
  src/physics_swe.c
  src/rdycore.c
  src/rdysetup.c
Labels: libceed

#89 Reduces memory allocation/deallocating within each time step
  include/private/rdycoreimpl.h
  include/private/rdysweimpl.h
  src/physics_swe.c
  src/rdysetup.c
  src/swe_flux_petsc.h
Labels: cleanup

#90 Ceed operator flux accumulation part 1: flux storage, code reorganization
  .github/workflows/clang-format-check.yml
  cmake/add_formatting_targets.cmake
  include/private/rdycoreimpl.h
  include/private/rdysweimpl.h
  src/CMakeLists.txt
  src/rdycore.c
  src/rdysetup.c
  src/swe/physics_swe.c
  src/swe/swe_flux_petsc.h
  src/swe/swe_operators.c
  src/swe/swe_operators.h
  src/swe/swe_operators_impl.h
  src/swe_setup_ceed.h
  src/time_series.c
Labels: cleanup, libceed

#91 This PR does some additional code cleanup.
  include/private/rdycoreimpl.h
  include/private/rdysweimpl.h
  src/CMakeLists.txt
  src/rdysetup.c
  src/swe/physics_swe.c
  src/swe/swe_ceed_operators.c
  src/swe/swe_flux_petsc.c
  src/swe/swe_operators.h
Labels: cleanup

#93 Adds support for Dirichlet BCs
  driver/main.F90
  driver/main.c
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/ex2b_dirichlet_bc.yaml
  include/finclude/rdycore.h
  include/private/rdyconfigimpl.h
  include/private/rdysweimpl.h
  include/rdycore.h.in
  src/f90-mod/rdycore.F90
  src/rdydata.c
  src/rdysetup.c
  src/swe/swe_flux_petsc.c
Labels: enhancement

#94 Implemented Dirichlet BCs with CEED and cleaned up water source updates
  driver/main.F90
  driver/main.c
  driver/tests/swe_roe/CMakeLists.txt
  include/finclude/rdycore.h
  include/private/rdycoreimpl.h
  include/private/rdysweimpl.h
  include/rdycore.h.in
  src/CMakeLists.txt
  src/f90-mod/rdycore.F90
  src/rdydata.c
  src/rdysetup.c
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
Labels: enhancement, cleanup, libceed

#97 Updates the C and Fortran drivers to run the Houston Harvey Flooding
  driver/main.F90
  driver/main.c
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/Houston1km.DirichletBC.yaml
  share/CMakeLists.txt
  share/conditions/DamBreak_grid5x10_wetdownstream.IC
  share/conditions/Houston1km.BC.bin
  share/conditions/Houston1km.IC
  share/conditions/Houston1km.Rain.bin
  share/conditions/four_mounds_60x24.ic
  share/meshes/Houston1km_with_z.exo
  src/swe/swe_petsc.c
  src/time_series.c
Labels: enhancement

#98 Removes RDycore memory-related functions in favor of using PETSc's.
  driver/main.c
  include/private/rdymemoryimpl.h
  src/rdycore.c
  src/rdymesh.c
  src/rdysetup.c
  src/read_config_file.c
  src/swe/physics_swe.c
  src/swe/swe_petsc.c
  src/time_series.c
  src/write_xdmf_output.c
Labels: bug-fix, cleanup

#99 Returns PETSC_SUCCESS instead of 0
  src/print_config.c
  src/rdyadvance.c
  src/rdycore.c
  src/rdydata.c
  src/rdymesh.c
  src/rdysetup.c
  src/read_config_file.c
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
  src/swe/swe_petsc.c
  src/tests/test_rdymesh.c
  src/time_series.c
  src/write_xdmf_output.c
Labels: cleanup

#101 Makes it possible to run with only time series as output
  include/private/rdyconfigimpl.h
  src/rdyadvance.c
  src/read_config_file.c
Labels: I/O, bug-fix

#103 Finished implementation of CEED accumulated boundary fluxes
  include/private/rdycoreimpl.h
  include/private/rdysweimpl.h
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
  src/time_series.c
Labels: cleanup, libceed

#105 Boundary flux metadata is now determined on initialization.
  include/private/rdycoreimpl.h
  src/time_series.c
Labels: performance
