Repository RDycore/RDycore, pull requests merged in 2023-05, with the labels that each got.

#38 Updates InitBoundaries() for MPI run
  src/rdysetup.c
Labels: bug-fix

#36 Implemented XDMF output
  CMakeLists.txt
  cmake/FindPETSc.cmake
  driver/tests/swe_roe/ex2b.yaml
  driver/tests/swe_roe/ex2b_ic_file.yaml
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  src/CMakeLists.txt
  src/cgns_output.c
  src/print_config.c
  src/rdyrun.c
  src/rdysetup.c
  src/read_config_file.c
  src/tests/test_read_config_file.c
  src/write_output.c
  src/xdmf_output.c
Labels: enhancement, I/O, bug-fix

#42 Minor updates to support verification runs
  .gitignore
  driver/tests/swe_roe/ex2b_ic_file.yaml
  include/private/rdyconfigimpl.h
  src/physics_swe.c
  src/rdysetup.c
  src/read_config_file.c
  src/write_output.c
Labels: enhancement
