Repository RDycore/RDycore, pull requests merged in 2024-09, with the labels that each got.

#208 Added a section describing sediment transport.
  docs/theory/sediment.md
  docs/theory/swe.md
  mkdocs.yml
Labels: documentation

#210 Adds adaptive time stepping based on CFL condition
  docs/common/input.md
  docs/developer/ceed.md
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/ex2b_ic_file_with_adapt.yaml
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  include/private/rdysweimpl.h
  src/rdyadvance.c
  src/rdysetup.c
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
  src/swe/swe_ceed_impl.h
  src/yaml_input.c
Labels: enhancement

#213 Now building libcyaml in our own build system, for simplicity.
  external/CMakeLists.txt
Labels: build system

#215 Adds a new struct for edge-related quantities
  include/private/rdycoreimpl.h
  include/private/rdysweimpl.h
  src/rdycore.c
  src/swe/physics_swe.c
  src/swe/swe_petsc.c
  src/time_series.c
Labels: cleanup
