Repository RDycore/RDycore, pull requests merged in 2024-10, with the labels that each got.

#223 Reordered parsing of ensemble members and math expressions to fix an issue.
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/ex2b-ensemble.yaml
  src/rdysetup.c
  src/yaml_input.c
Labels: I/O, bug-fix, ensembles

#226 Operator refactor part 1: renaming and regrouping
  CMakeLists.txt
  docs/theory/sediment.md
  include/private/rdycoreimpl.h
  include/private/rdysweimpl.h
  src/CMakeLists.txt
  src/checkpoint.c
  src/rdyadvance.c
  src/rdycore.c
  src/rdydata.c
  src/rdydm.c
  src/rdymms.c
  src/rdysetup.c
  src/solvers.c
  src/swe/physics_swe.c
  src/swe/swe_petsc.c
  src/time_series.c
  src/xdmf_output.c
Labels: cleanup, libceed

#227 Operator refactor part 2: moving stuff out of the SWE-specific operators
  .gitignore
  driver/main.F90
  driver/tests/swe_roe/CMakeLists.txt
  include/private/rdycoreimpl.h
  include/private/rdyoperatordataimpl.h
  include/private/rdysweimpl.h
  include/rdycore.h.in
  src/CMakeLists.txt
  src/f90-mod/rdycore.F90
  src/operator_data.c
  src/rdycore.c
  src/rdydata.c
  src/rdydm.c
  src/rdymms.c
  src/rdysetup.c
  src/solvers.c
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
  src/time_series.c
Labels: cleanup, libceed

#228 Adds few destroy functions
  include/private/rdycoreimpl.h
  include/private/rdydmimpl.h
  src/operator_data.c
  src/rdycore.c
  src/rdydm.c
  src/swe/physics_swe.c
Labels: enhancement, AMR

#230 Added output.directory option for specifying an output directory.
  docs/common/input.md
  driver/tests/swe_roe/ex2b_dirichlet_bc.yaml
  include/private/rdyconfigimpl.h
  src/rdyadvance.c
  src/yaml_input.c
Labels: enhancement, I/O

#231 Updates PETSc settings on Frontier
  config/set_petsc_settings.sh
Labels: frontier
