Repository RDycore/RDycore, pull requests merged in 2024-02, with the labels that each got.

#130 Improved error checking for specified flow conditions
  driver/tests/swe_roe/ex2b_ic_file.yaml
  driver/tests/swe_roe/four_mounds_60x24.yaml
  src/rdysetup.c
Labels: bug-fix

#118 Fixes XDMF output
  .github/workflows/auto_test.yml
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/mixed_elements.yaml
  driver/tests/swe_roe/mixed_elements_ic_file.yaml
  driver/tests/swe_roe/mixed_elemnts_ic_file.yaml
  include/private/rdydmimpl.h
  include/private/rdymeshimpl.h
  share/conditions/DamBreak_grid5x10_mixed_elements_wetdownstream.ic.int32.bin
  share/conditions/DamBreak_grid5x10_mixed_elements_wetdownstream.ic.int64.bin
  share/materials/manning_grid5x10_mixed_elements.int32.bin
  share/materials/manning_grid5x10_mixed_elements.int64.bin
  share/meshes/DamBreak_grid5x10_mixed_elements.exo
  share/meshes/Houston1km_with_z.exo
  src/CMakeLists.txt
  src/rdydm.c
  src/rdymesh.c
  src/rdysetup.c
  src/tests/test_rdymesh.c
  src/xdmf_output.c
Labels: enhancement

#131 Fixed some parallel hangs in file-related ICs/material properties.
  src/rdysetup.c
Labels: I/O, bug-fix

#132 Adds remove the debugging code that was mistakenly added
  src/rdymesh.c
  src/rdysetup.c
Labels: bug-fix

#134 Implemented checkpoints and restarts (binary working, HDF5 not)
  docs/user/input.md
  driver/main.F90
  driver/main.c
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/ex2b.yaml
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  include/rdycore.h.in
  src/CMakeLists.txt
  src/checkpoint.c
  src/f90-mod/rdycore.F90
  src/rdyadvance.c
  src/rdycore.c
  src/rdysetup.c
  src/tests/test_yaml_input.c
  src/yaml_input.c
Labels: I/O
