Repository RDycore/RDycore, pull requests merged in 2024-03, with the labels that each got.

#136 Fixes HDF5 restart behavior
  cmake/FindPETSc.cmake
  driver/tests/swe_roe/CMakeLists.txt
  src/checkpoint.c
  src/rdydm.c
  src/yaml_input.c
Labels: I/O

#139 Updates mesh creation to remove few assumptions
  include/private/rdymeshimpl.h
  src/rdymesh.c
Labels: enhancement, mesh and discretization

#143 Corrects the DM for global-to-local scatter
  src/rdysetup.c
Labels: bug-fix

#135 Adds configuration files for PETSc
  config/README.md
  config/install.aurora.oneapi.opt.32bit.sh
  config/install.aurora.oneapi.opt.64bit.sh
  config/install.frontier.gnugpu.opt.32bit.sh
  config/install.frontier.gnugpu.opt.64bit.sh
  config/install.pm-cpu.gnu.opt.32bit.sh
  config/install.pm-cpu.gnu.opt.64bit.sh
  config/install.pm-gpu.gnugpu.opt.32bit.sh
  config/install.pm-gpu.gnugpu.opt.64bit.sh
  config/modules.aurora.oneapi
  config/modules.frontier.gnugpu
  config/modules.pm-cpu.gnu
  config/modules.pm-gpu.gnugpu
  config/set_petsc_settings.sh
  docs/installation.md
Labels: documentation, build system

#145 Adds a check for the global vertex ID
  src/rdymesh.c
Labels: bug-fix

#147 Updates the XDMF output
  include/private/rdymeshimpl.h
  src/rdymesh.c
  src/xdmf_output.c
Labels: enhancement, I/O

#150 Uses PetscCallCEED
  src/rdysetup.c
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
  src/time_series.c
Labels: enhancement

#149 Adds prefix to boundary_fluxes.dat file
  src/time_series.c
Labels: bug-fix

#142 Ensembles, part 1: defining and running
  docs/user/input.md
  driver/tests/swe_roe/ex2b-ensemble.yaml
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  include/private/rdylogimpl.h
  src/CMakeLists.txt
  src/checkpoint.c
  src/ensemble.c
  src/rdyadvance.c
  src/rdycore.c
  src/rdymesh.c
  src/rdysetup.c
  src/time_series.c
  src/xdmf_output.c
  src/yaml_input.c
Labels: documentation, enhancement, I/O, UQ

#152 Calling ConfigureEnsembleMember with PetscCall.
  src/yaml_input.c
Labels: bug-fix

#158 Adds a check to make sure that all declared boundaries are in the grid file.
  driver/tests/CMakeLists.txt
  driver/tests/bad_input/CMakeLists.txt
  driver/tests/bad_input/nonexistent_boundary.yaml
  src/rdysetup.c
Labels: I/O, bug-fix

#159 Switched to pkgconfig method for finding PETSc and friends.
  CMakeLists.txt
  cmake/FindPETSc.cmake
  driver/tests/CMakeLists.txt
  driver/tests/bad_input/CMakeLists.txt
  driver/tests/swe_roe/CMakeLists.txt
  external/CMakeLists.txt
  src/CMakeLists.txt
  src/f90-mod/tests/CMakeLists.txt
  src/tests/CMakeLists.txt
Labels: build system
