Repository RDycore/RDycore, pull requests merged in 2024-05, with the labels that each got.

#174 Method of Manufactured Solutions, part 2: convergence studies
  docs/user/index.md
  docs/user/mms.md
  driver/mms.F90
  driver/mms.c
  driver/tests/swe_roe/mms_dx1.yaml
  include/private/rdymmsconfigimpl.h
  include/rdycore.h.in
  src/f90-mod/rdycore.F90
  src/rdymms.c
  src/rdysetup.c
  src/swe/physics_swe.c
  src/yaml_input.c
Labels: enhancement, testing, bug-fix

#175 Mesh vertices are now snapped to z(x, y) even when unrefined.
  docs/index.md
  driver/tests/swe_roe/mms_dx1.yaml
  src/rdymms.c
Labels: bug-fix

#178 Draft Developer guide
  CMakeLists.txt
  docs/common/input.md
  docs/common/installation.md
  docs/common/mms.md
  docs/developer/development.md
  docs/developer/e3sm.md
  docs/developer/index.md
  docs/developer/organization.md
  docs/developer/style.md
  docs/developer/tools.md
  docs/index.md
  docs/user/index.md
  mkdocs.yml
Labels: documentation

#180 Updates the constant rainfall rate
  driver/main.c
Labels: bug-fix

#181 Fixes the global edge ID for serial runs
  src/rdymesh.c
Labels: bug-fix
