Repository RDycore/RDycore, pull requests merged in 2024-06, with the labels that each got.

#177 Removes one VecCopy and allocates another Vec at model initialization
  include/private/rdycoreimpl.h
  include/private/rdymeshimpl.h
  src/rdycore.c
  src/rdydata.c
  src/rdydm.c
  src/rdymesh.c
  src/rdymms.c
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
  src/tests/test_rdymesh.c
Labels: performance

#176 Updates to support coupling with E3SM
  include/rdycore.h.in
  src/f90-mod/rdycore.F90
  src/rdydata.c
  src/rdysetup.c
Labels: E3SM coupling

#186 Trivial typo fix.
  mkdocs.yml
Labels: documentation

#188 Removed build info from README.md, adding links to static doc site.
  README.md
  docs/common/installation.md
  docs/developer/development.md
Labels: documentation

#190 Adding PETSc library directory to RPATH.
  CMakeLists.txt
Labels: build system

#192 Removed `bed_friction` parameter from YAML spec.
  .gitignore
  docs/common/input.md
  include/private/rdyconfigimpl.h
  src/tests/test_yaml_input.c
  src/yaml_input.c
Labels: I/O, bug-fix

#189 Adds notes about the mesh
  docs/developer/figures/quad_tri_mesh_dmplex_numbering_N1.png
  docs/developer/figures/quad_tri_mesh_dmplex_numbering_N2.png
  docs/developer/figures/quad_tri_mesh_exodus_ii.png
  docs/developer/index.md
  docs/developer/mesh.md
Labels: documentation, mesh and discretization

#193 Update information about running RDycore on Perlmutter and Frontier
  config/install.pm-cpu.gnu.hdf5_1_14_3.debug.64bit.sh
  config/install.pm-cpu.gnu.hdf5_1_14_3.opt.64bit.sh
  config/install.pm-gpu.gnugpu.hdf5_1_14_3.debug.64bit.sh
  config/install.pm-gpu.gnugpu.hdf5_1_14_3.opt.64bit.sh
  config/set_petsc_settings.sh
  docs/common/installation.md
  docs/user/example-cases/dam-break/dam-break-initial-condition.png
  docs/user/example-cases/dam-break/frontier.batch.base
  docs/user/example-cases/dam-break/index.md
  docs/user/example-cases/dam-break/inputdeck_5120x2560.yaml
  docs/user/example-cases/dam-break/perlmutter.batch.base
  docs/user/example-cases/dam-break/setup_batch_for_dam_break.sh
  docs/user/example-cases/example-cases.md
  mkdocs.yml
Labels: documentation
