Repository RDycore/RDycore, pull requests merged in 2024-01, with the labels that each got.

#121 Adds C and Fortran MMS drivers
  CMakeLists.txt
  driver/CMakeLists.txt
  driver/main.F90
  driver/mms.F90
  driver/mms.c
  driver/tests/CMakeLists.txt
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/mms_dx1.yaml
  include/rdycore.h.in
  share/meshes/mms_triangles_dx1.exo
  src/f90-mod/rdycore.F90
  src/rdydata.c
Labels: testing

#123 Boundaries and boundary conditions are now constructed after domain decomposition
  src/rdysetup.c
Labels: bug-fix

#124 Fixes application of BC for CEED.
  .github/workflows/clang-format-check.yml
  driver/mms.c
  src/swe/swe_ceed.c
Labels: bug-fix, libceed
