Repository RDycore/RDycore, pull requests merged in 2024-11, with the labels that each got.

#234 Adds support for specifying multiple homogeneous datasets for boundary and source sink conditions
  driver/main.c
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/quad_tri_mesh.yaml
  include/finclude/rdycore.h
  include/private/rdyconfigimpl.h
  include/private/rdyoperatordataimpl.h
  include/rdycore.h.in
  share/meshes/quad_tri_mesh.exo
  src/operator_data.c
  src/rdycore.c
  src/rdydata.c
  src/rdymms.c
  src/rdysetup.c
  src/xdmf_output.c
  src/yaml_input.c
Labels: enhancement, bug-fix

#237 Fixes seg fault when writing flux data
  config/modules.pm-cpu.gnu
  config/modules.pm-gpu.gnugpu
  src/time_series.c
Labels: bug-fix

#239 Corrects the computation of CFL when using CEED
  src/swe/physics_swe.c
Labels: bug-fix

#240 Very minor updates to README, and compiler warning fixes.
  README.md
  driver/main.c
  src/checkpoint.c
Labels: documentation, cleanup

#241 Moving some files around in preparation for refactor of "operators."
  docs/developer/organization.md
  include/private/rdyboundaryimpl.h
  include/private/rdycoreimpl.h
  include/private/rdyoperatorimpl.h
  src/CMakeLists.txt
  src/operator.c
  src/rdyadvance.c
  src/rdycore.c
  src/rdydata.c
  src/rdymms.c
  src/rdysetup.c
  src/swe/swe.c
Labels: cleanup

#242 Separates out CEED resource/context management.
  driver/main.c
  include/private/rdycoreimpl.h
  src/CMakeLists.txt
  src/ceed.c
  src/operator.c
  src/rdycore.c
  src/rdydata.c
  src/rdydm.c
  src/rdysetup.c
  src/swe/swe.c
  src/time_series.c
Labels: cleanup, libceed

#243 Separated courant number diagnostic core logic from SWE operator.
  include/private/rdycoreimpl.h
  src/CMakeLists.txt
  src/courant.c
  src/rdycore.c
  src/swe/swe.c
Labels: cleanup

#245 Changes OperatorSourceData interface to be region-aware.
  driver/main.F90
  driver/main.c
  include/private/rdycoreimpl.h
  include/private/rdymeshimpl.h
  include/private/rdyoperatorimpl.h
  include/private/rdyregionimpl.h
  include/rdycore.h.in
  src/f90-mod/rdycore.F90
  src/f90-mod/tests/test_coupling.F90
  src/operator.c
  src/rdycore.c
  src/rdydata.c
  src/rdymesh.c
  src/rdymms.c
  src/rdysetup.c
  src/swe/swe_ceed.c
  src/swe/swe_petsc.c
  src/time_series.c
Labels: cleanup
