Repository RDycore/RDycore, pull requests merged in 2024-04, with the labels that each got.

#163 Minor PETSc pkgconfig fixes, part 1
  CMakeLists.txt
  cmake/extract_petsc_variable.cmake
Labels: build system, bug-fix

#164 Pkgconfig changes, part 2
  CMakeLists.txt
  cmake/extract_petsc_variable.cmake
Labels: build system

#161 Adds support spatially distributed rainfall dataset
  driver/main.c
  driver/tests/swe_roe/CMakeLists.txt
  share/conditions/2017-08-26:00-00.int32.bin
  share/conditions/2017-08-26:00-00.int64.bin
  share/conditions/2017-08-26:01-00.int32.bin
  share/conditions/2017-08-26:01-00.int64.bin
Labels: enhancement

#166 Uses PetscInt_FMT instead of `%d`
  src/checkpoint.c
  src/ensemble.c
  src/rdyadvance.c
  src/rdydata.c
  src/rdysetup.c
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
Labels: cleanup

#167 Fixes the computation of next coupling time
  src/rdyadvance.c
Labels: bug-fix

#168 Adjustments to the build system to address an issue observed by Matt.
  CMakeLists.txt
Labels: build system

#169 Few minor updates to support E3SM-RDycore coupling for more than 1 proc
  include/rdycore.h.in
  src/f90-mod/rdycore.F90
  src/f90-mod/tests/test_coupling.F90
  src/rdydata.c
  src/rdymesh.c
Labels: enhancement, E3SM coupling

#153 Fixes error catching for setting PETSc on supported machines
  config/install.frontier.gnugpu.debug.32bit.sh
  config/install.frontier.gnugpu.debug.64bit.sh
  config/set_petsc_settings.sh
Labels: bug-fix

#171 Exposing time units to interface header and adding to time-related functions
  driver/main.F90
  driver/main.c
  driver/mms.F90
  driver/mms.c
  include/private/rdyconfigimpl.h
  include/rdycore.h.in
  src/f90-mod/rdycore.F90
  src/f90-mod/tests/test_coupling.F90
  src/rdyadvance.c
  src/rdysetup.c
  src/yaml_input.c
Labels: cleanup

#173 Removes an unnecessary check
  driver/tests/swe_roe/ex2b_ic_file.yaml
  src/rdymesh.c
Labels: bug-fix

#172 Method of Manufactured Solutions, part 1: more expressive driver input
  cmake/add_formatting_targets.cmake
  docs/user/input.md
  docs/user/mms.md
  driver/main.F90
  driver/main.c
  driver/mms.F90
  driver/mms.c
  driver/tests/bad_input/nonexistent_boundary.yaml
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/Houston1km.DirichletBC.yaml
  driver/tests/swe_roe/ex2b-ensemble.yaml
  driver/tests/swe_roe/ex2b.yaml
  driver/tests/swe_roe/ex2b_dirichlet_bc.yaml
  driver/tests/swe_roe/mixed_elements.yaml
  driver/tests/swe_roe/mms_dx1.yaml
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  include/private/rdydmimpl.h
  include/private/rdymmsconfigimpl.h
  include/rdycore.h.in
  mkdocs.yml
  src/CMakeLists.txt
  src/f90-mod/rdycore.F90
  src/f90-mod/tests/coupling.yaml
  src/f90-mod/tests/test_coupling.F90
  src/rdydata.c
  src/rdydm.c
  src/rdymms.c
  src/rdysetup.c
  src/swe/physics_swe.c
  src/swe/swe_ceed.c
  src/tests/test_yaml_input.c
  src/yaml_input.c
  tools/Dockerfile.petsc
  tools/build-petsc-docker-images.sh
Labels: enhancement, testing, fortran, I/O, cleanup, driver
