Repository RDycore/RDycore, pull requests merged in 2025-03, with the labels that each got.

#286 Adds a shell script for configuring a ELM-RDycore on Perlmutter for ROS event
  docs/user/example-cases/e3sm-cases/ros-events/e3sm_rdycore_ros_events.sh
Labels: E3SM coupling

#288 Added a FAQ to the installation section with advice about PETSc/pkg-config.
  docs/common/installation.md
Labels: documentation

#289 Consolidating self-contained CEED backend JIT header generation.
  .github/workflows/auto_test.yml
  include/private/physics_ceed.h.in
  src/CMakeLists.txt
  src/sediment/sediment_ceed.h.in
  src/swe/swe_ceed.h.in
Labels: cleanup, libceed

#291 Fixes mesh output
  src/rdymesh.c
Labels: bug-fix
