Repository RDycore/RDycore, pull requests merged in 2025-02, with the labels that each got.

#279 Minor operator cleanup before Q-function reorganization
  docs/theory/sediment.md
  docs/theory/swe.md
  include/private/rdydmimpl.h
  include/private/rdyoperatorimpl.h
  include/rdycore.h.in
  src/operator.c
  src/rdydata.c
  src/rdymms.c
  src/rdysetup.c
  src/sediment/sediment_ceed.c
  src/sediment/sediment_ceed_impl.h
  src/sediment/sediment_petsc.c
  src/swe/swe_ceed.c
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
Labels: cleanup

#280 CEED Q function reorganization, part 1: consolidating operator constructors
  include/private/rdyoperatorimpl.h
  include/private/rdysedimentimpl.h
  include/private/rdysweimpl.h
  src/CMakeLists.txt
  src/operator.c
  src/operator_ceed.c
  src/operator_diagnostics.c
  src/operator_petsc.c
  src/sediment/sediment_ceed.c
  src/swe/swe_ceed.c
Labels: cleanup

#281 Fixes for running the Amazon lake problem in parallel
  driver/main.c
  src/rdydata.c
  src/rdymms.c
  src/rdysetup.c
Labels: bug-fix

#282 CEED Q function reorganization, part 2: refactoring SWE and sediment Q functions
  docs/theory/swe.md
  src/sediment/sediment_ceed_impl.h
  src/sediment/sediment_roe_ceed_impl.h
  src/swe/swe_ceed_impl.h
  src/swe/swe_roe_ceed_impl.h
Labels: cleanup, libceed

#283 Reorganized PETSc SWE and sediment operators to resemble reorganized CEED operators.
  src/sediment/sediment_petsc.c
  src/sediment/sediment_petsc_impl.h
  src/sediment/sediment_roe_petsc_impl.h
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
  src/swe/swe_petsc_impl.h
  src/swe/swe_roe_petsc_impl.h
Labels: cleanup

#284 Adopt Jed's suggestion for avoiding C99/C++20 features in headers.
  src/sediment/sediment_ceed_impl.h
  src/swe/swe_ceed_impl.h
Labels: bug-fix, libceed

#285 Fixes CUDA issues discovered with local GPU.
  .gitignore
  CMakeLists.txt
  include/private/config.h.in
  include/private/rdyoperatorimpl.h
  include/rdycore.h
  src/CMakeLists.txt
  src/operator.c
  src/operator_ceed.c
  src/rdydata.c
  src/rdymms.c
  src/rdysetup.c
  src/sediment/sediment_ceed.h.in
  src/sediment/sediment_ceed_impl.h
  src/swe/swe_ceed.h.in
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
Labels: bug-fix
