Repository RDycore/RDycore, pull requests merged in 2025-01, with the labels that each got.

#252 Major restructuring of RDycore to support sediment/salinity transport
  CMakeLists.txt
  docs/developer/operators.md
  docs/theory/swe.md
  driver/CMakeLists.txt
  driver/main.F90
  driver/main.c
  driver/tests/CMakeLists.txt
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/mms_conv_study.yaml
  driver/tests/swe_roe/mms_single_run.yaml
  include/private/rdyconditionimpl.h
  include/private/rdycoreimpl.h
  include/private/rdydmimpl.h
  include/private/rdyoperatorimpl.h
  include/private/rdysweimpl.h
  include/rdycore.h.in
  src/CMakeLists.txt
  src/ceed.c
  src/checkpoint.c
  src/ensemble.c
  src/f90-mod/CMakeLists.txt
  src/f90-mod/rdycore.F90
  src/f90-mod/tests/CMakeLists.txt
  src/f90-mod/tests/test_coupling.F90
  src/operator.c
  src/operator_diagnostics.c
  src/rdyadvance.c
  src/rdycore.c
  src/rdydata.c
  src/rdydm.c
  src/rdymesh.c
  src/rdymms.c
  src/rdysetup.c
  src/swe/swe.c
  src/swe/swe_ceed.c
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
  src/tests/CMakeLists.txt
  src/time_series.c
  src/xdmf_output.c
  src/yaml_input.c
Labels: documentation, enhancement, testing, fortran, I/O, bug-fix, cleanup, libceed, driver

#254 Added an option to write the grid to a separate file (XDMF only).
  docs/common/input.md
  driver/tests/swe_roe/Simons.OceanDirichletBC.yaml
  include/private/rdyconfigimpl.h
  src/xdmf_output.c
  src/yaml_input.c
Labels: enhancement, I/O

#250 Updates module for Frontier
  config/modules.frontier.gnugpu
  config/set_petsc_settings.sh
Labels: frontier

#255 Adds the implicit treatment of the friction term
  README.md
  docs/common/input.md
  driver/tests/swe_roe/ex2b.yaml
  include/private/rdyconfigimpl.h
  include/private/rdysweimpl.h
  src/operator.c
  src/swe/swe_ceed.c
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
  src/yaml_input.c
Labels: enhancement

#259 Use P0 discretization for layout
  docs/common/installation.md
  src/f90-mod/rdycore.F90
  src/rdydm.c
  src/rdymesh.c
  src/yaml_input.c
Labels: enhancement, mesh and discretization

#264 Updates CreateSequentialVector to set block size.
  src/operator.c
Labels: bug-fix

#263 Removed an unnecessary check in operator creation.
  src/operator.c
Labels: bug-fix

#257 Adds sediment dynamics
  docs/developer/organization.md
  driver/main.F90
  driver/main.c
  driver/tests/CMakeLists.txt
  driver/tests/sediment/CMakeLists.txt
  driver/tests/sediment/sediment.yaml
  driver/tests/sediment/sediment_ic_file.yaml
  driver/tests/sediment/sediment_mms_conv_study.yaml
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  include/private/rdydmimpl.h
  include/private/rdymmsconfigimpl.h
  include/private/rdyoperatorimpl.h
  include/private/rdysedimentimpl.h
  include/rdycore.h.in
  share/conditions/DamBreak_grid5x10_wetdownstream.sediment_ic.int32.bin
  share/conditions/DamBreak_grid5x10_wetdownstream.sediment_ic.int64.bin
  src/CMakeLists.txt
  src/f90-mod/rdycore.F90
  src/operator.c
  src/rdydata.c
  src/rdydm.c
  src/rdymms.c
  src/rdysetup.c
  src/sediment/sediment_petsc.c
  src/tests/test_yaml_input.c
  src/yaml_input.c
Labels: enhancement

#267 Adds CEED version of the sediment dynamics
  driver/tests/sediment/CMakeLists.txt
  include/private/rdysedimentimpl.h
  src/CMakeLists.txt
  src/operator.c
  src/sediment/sediment_ceed.c
  src/sediment/sediment_ceed_impl.h
Labels: enhancement, libceed, sediment

#268 Some minor cleanup, and adding sanitizers to CI builds.
  .github/workflows/auto_test.yml
  src/rdyadvance.c
  src/rdydm.c
  src/rdysetup.c
  src/swe/swe_petsc.c
  tools/README.md
  tools/lsan_suppr.txt
Labels: build system, testing, bug-fix

#270 Fixes the E3SM-RDycore script
  docs/user/example-cases/e3sm-cases/harvey-flooding/e3sm_rdycore_harvey_flooding.sh
Labels: documentation

#273 Adds velocity regularization
  docs/common/input.md
  include/private/rdyconfigimpl.h
  include/private/rdysweimpl.h
  src/operator.c
  src/swe/swe_ceed.c
  src/swe/swe_ceed_impl.h
  src/swe/swe_petsc.c
  src/yaml_input.c
Labels: enhancement

#272 Extends sediment dynamics to allow more than one sediment class.
  CMakeLists.txt
  README.md
  cmake/generate_cyaml_sediment_fields.cmake
  docs/common/input.md
  docs/common/mms.md
  driver/tests/sediment/CMakeLists.txt
  driver/tests/sediment/sediment.yaml
  driver/tests/sediment/sediment_ic_file.yaml
  driver/tests/sediment/sediment_mms_conv_study.yaml
  driver/tests/swe_roe/CMakeLists.txt
  driver/tests/swe_roe/mms_conv_study.yaml
  include/private/rdyconditionimpl.h
  include/private/rdyconfigimpl.h
  include/private/rdycoreimpl.h
  include/private/rdydmimpl.h
  include/private/rdymmsconfigimpl.h
  include/private/rdysedimentimpl.h
  include/rdycore.h.in
  src/operator.c
  src/rdydata.c
  src/rdydm.c
  src/rdymms.c
  src/rdysetup.c
  src/sediment/sediment_ceed.c
  src/sediment/sediment_ceed_impl.h
  src/sediment/sediment_petsc.c
  src/tests/test_yaml_input.c
  src/yaml_input.c
Labels: enhancement, sediment

#274 Cleans up SWE operator constructors, similar to sediment operators
  include/private/rdysweimpl.h
  src/operator.c
  src/swe/swe_ceed.c
  src/swe/swe_petsc.c
Labels: cleanup
